// Generated by curl-to-Go: https://mholt.github.io/curl-to-go

// curl -v -X POST http://wso-2-republish-api-git-wso2-helper.apps.paas.maucash.id/republishapi

package main

import (
	"fmt"
	"log"
	"net/http"
)

func main() {
	resp, err := http.Post("http://wso-2-republish-api-git-wso2-helper.apps.paas.maucash.id/republishapi", "", nil)
	log.Println(resp)
	if err != nil {
		log.Fatal(err)
	}
	defer resp.Body.Close()

	http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprintln(w, "halo!")
	})

	fmt.Println("starting web server at http://localhost:8080/")
	http.ListenAndServe(":8080", nil)
}
